%DEMO_UAV_ACOUSTICS Example usage of the UAV acoustic emulator toolbox.
%
%   Run this script directly (F5 or `demo_uav_acoustics` at the command
%   line) after adding this folder to your MATLAB path.

clear; clc; close all;

%% ------------------------------------------------------------------
%  Example 1: 5-microphone array, straight-line UAV pass
%  ------------------------------------------------------------------
fs = 4000;                     % Hz
duration = 10;                 % seconds
t = (0:1/fs:duration)';

micXY_5 = [ ...
     0   0;
    50   0;
     0  50;
   -50   0;
     0 -50];

uavXYZ_5 = generate_uav_trajectory(t, 'straight', ...
    'startXY', [-200 -30], 'endXY', [200 30], 'altitude', 80);

[Y5, t5, meta5, extras5] = simulate_uav_acoustics(micXY_5, uavXYZ_5, t, ...
    'sourceType', 'rotor', ...
    'sourceFreq', 120, ...
    'snrDb', 12, ...
    'alpha', 1, ...
    'enableDoppler', true, ...
    'enableReflection', false, ...
    'seed', 1);

fprintf('Example 1: %d mics, %d samples, fs = %d Hz\n', ...
    size(Y5, 2), size(Y5, 1), fs);

save_simulation('demo_run_5mic.mat', Y5, t5, meta5, extras5);
plot_simulation_results(Y5, t5, meta5, 'micIndices', 1:5, 'spectrogramMic', 1);

%% ------------------------------------------------------------------
%  Example 2: 20-microphone grid, arcing UAV path with reflection
%  ------------------------------------------------------------------
[gridX, gridY] = meshgrid(-80:40:80, -80:40:80); % 5x5 = 25 -> take first 20
micXY_20 = [gridX(:), gridY(:)];
micXY_20 = micXY_20(1:20, :);

uavXYZ_20 = generate_uav_trajectory(t, 'arc', ...
    'center', [0 0], 'radius', 150, ...
    'startAngle', 0, 'endAngle', pi, 'altitude', 100);

[Y20, t20, meta20, extras20] = simulate_uav_acoustics(micXY_20, uavXYZ_20, t, ...
    'sourceType', 'multitone', ...
    'sourceFreq', 90, ...
    'snrDb', 8, ...
    'alpha', 1.2, ...
    'enableDoppler', true, ...
    'enableReflection', true, ...
    'noiseType', 'pink', ...
    'dropoutRate', 0.1, ...
    'seed', 7);

fprintf('Example 2: %d mics, %d samples, fs = %d Hz\n', ...
    size(Y20, 2), size(Y20, 1), fs);

save_simulation('demo_run_20mic.mat', Y20, t20, meta20, extras20);
plot_simulation_results(Y20, t20, meta20, 'micIndices', 1:4, 'spectrogramMic', 3);

%% ------------------------------------------------------------------
%  Example 3: Loiter pattern with a broadband noise-burst source
%  ------------------------------------------------------------------
uavXYZ_loiter = generate_uav_trajectory(t, 'loiter', ...
    'center', [0 0], 'radius', 60, 'numLoops', 3, 'altitude', 50);

[Yl, tl, metal] = simulate_uav_acoustics(micXY_5, uavXYZ_loiter, t, ...
    'sourceType', 'noiseburst', ...
    'snrDb', 5, ...
    'enableDoppler', false, ...
    'seed', 3);

fprintf('Example 3 (loiter): %d mics, %d samples\n', size(Yl,2), size(Yl,1));
plot_simulation_results(Yl, tl, metal, 'showSpectrogram', false);
